version: "3.8"

services:
  app:
    container_name: recognition-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - recognition-mariadb

  recognition-mariadb:
    container_name: recognition-mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '@Compassion123'
      MARIADB_DATABASE: staff_recognition
      MARIADB_USER: staff_recognition
      MARIADB_PASSWORD: '@Compassion123'
    volumes:
      - data:/var/lib/mysql

  recognition-adminer:
    container_name: recognition-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - recognition-mariadb

volumes:
  data:

